apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hello-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cpu-hello-backend
  template:
    metadata:
      labels:
        app: cpu-hello-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-hello-backend
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: cpu-hello-backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
